### ISSUE TITLE
做个数据迁移的方法比较好

### ISSUE THREAD

**Issue by EspoirX** [forJrking/Preferences#1]

**Comment by forJrking** [comment]
> _No description provided._

大佬好！做了数据迁移功能getAll  文档还没改好 https://juejin.cn/post/6947244683093508104

**Comment by EspoirX** [comment]
我渣渣，好的，我看看

**Comment by forJrking** [comment]
> 我渣渣，好的，我看看

大佬凡尔赛了，你的开源库和文章我都用看过用过，非常棒👍🏻

**Comment by EspoirX** [comment]
你也是大佬，加个好友吗
![image](https://user-images.githubusercontent.com/16240767/117535731-b31b7180-b029-11eb-9647-29c2bcfe4950.png)
